#!/bin/bash
#reset File

source workflow.library

branch_name="testmaster";
                        
while [ "$1" != "" ]; do
    printf "\nRead next command argument as [$1]\n" >> debug.txt;
    if [ "$1" == "--merge-branch" ]
        then
        shift
	branch_name="$1";
        printf "%s\n" "Found custom merge branch flag with value of [$1] for branch name\n";
	shift
    else
    arguments="$arguments$1";
    # Shift all the parameters down by one
    shift
    fi;
done




lv=$(release_features $1);

cleanup_tmp_files;

